### ISSUE TITLE
Fix Warnings thrown in Sphinx doc build

### ISSUE THREAD

**Issue by MichalKononenko** [MichalKononenko/OmicronServer#81]
When building sphinx documentation, sphinx has problems importing ```views.users```. 

The following is a stack trace of the error

```
C:\SoftwareProjects\OmicronServer\docs\source\api_reference\views.rst:16: WARNING: autodoc: failed to import module 'views.users'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 722, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute '_set_parent_with_dispatch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\Sphinx-1.3.1-py3.4.egg\sphinx\ext\autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "C:\SoftwareProjects\OmicronServer\views\__init__.py", line 7, in <module>
    from views.users import UserContainer, UserView
  File "C:\SoftwareProjects\OmicronServer\views\users.py", line 7, in <module>
    from auth import auth
  File "C:\SoftwareProjects\OmicronServer\auth.py", line 12, in <module>
    from database import User, Token, ContextManagedSession
  File "C:\SoftwareProjects\OmicronServer\database\__init__.py", line 9, in <module>
    from database.models.users import User, Token, Administrator
  File "C:\SoftwareProjects\OmicronServer\database\models\__init__.py", line 7, in <module>
    from database import schema
  File "C:\SoftwareProjects\OmicronServer\database\schema.py", line 29, in <module>
    Column('date_joined', DateTime, nullable=False, default=datetime.utcnow())
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 416, in __new__
    metadata._remove_table(name, schema)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 182, in reraise
    raise value
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 411, in __new__
    table._init(name, metadata, *args, **kw)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 488, in _init
    self._init_items(*args)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 72, in _init_items
    item._set_parent_with_dispatch(self)
  File "C:\Anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 728, in __getattr__
    key)
AttributeError: Neither 'UnaryExpression' object nor 'Comparator' object has an attribute '_set_parent_with_dispatch'
```

**Comment by MichalKononenko** [comment]
Issue has been fixed in the ``DocumentationUpdate`` branch. No reason to believe that it propagated into master, as this would break the Travis build. Closing this issue now
